plugins:
  - jest
env:
  es2021: true
  jest/globals: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  # Включает поддержку конструкции import.meta.url
rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # разрешает подчёркивание в именах только для двух констант
  import/extensions: 0
  no-console: 0

